#!/bin/bash
dirname=$(dirname $0)
hooktype=$(basename $0)

[ -x "$dirname/gitty/update-shared-hooks" ] && . "$dirname/gitty/update-shared-hooks"
  
for base_dir in "${dirname}"/{shared,local}; do
  [ -d "${base_dir}/${hooktype}.d" ] || continue
  for script in "${base_dir}/${hooktype}.d"/*; do
    [ -x "$script" ] || continue
    HELPERS="${base_dir}/helpers" "${script}" "$*" || exit $?
  done
done
